### ISSUE TITLE
Service account access_token is None

### ISSUE THREAD

**Issue by karolyi** [google/google-api-python-client#137]
Hey,

I'm using the `google-api-python-client==1.4.2` and `oauth2client==1.5.1`, with service accounts in our internal SEO tool, which communicates with the webmaster tools API.

As I'm trying to *batch fix* crawl error samples, I get the following error:
```python
Traceback (most recent call last):
  File "/home/seodev/project/venv/lib/python3.4/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/seodev/project/venv/lib/python3.4/site-packages/django/views/decorators/http.py", line 45, in inner
    return func(request, *args, **kwargs)
  File "/home/seodev/project/venv/lib/python3.4/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "./visualizer/seo/views.py", line 339, in json_sample_markfixed_many
    result_json = cese_markfixed_many(request, id_list)
  File "./visualizer/seo/utils.py", line 571, in cese_markfixed_many
    exc_callback_item=exc_item, exc_callback_batch=exc_batch)
  File "./collector_gapi/batch_handler.py", line 253, in run_batch
    item_list, service_func, batch_parse_response, batch_request_dict)
  File "./collector_gapi/batch_handler.py", line 94, in calculate_ideal_length
    item_list, 1, service_func, callback, batch_request_dict)
  File "./collector_gapi/batch_handler.py", line 72, in compile_batch
    return batch, get_payload_size(batch)
  File "./collector_gapi/batch_handler.py", line 42, in get_payload_size
    body = batch._serialize_request(request)
  File "/home/seodev/project/venv/lib/python3.4/site-packages/googleapiclient/http.py", line 1101, in _serialize_request
    request.http.request.credentials.apply(headers)
  File "/home/seodev/project/venv/lib/python3.4/site-packages/oauth2client/client.py", line 643, in apply
    headers['Authorization'] = 'Bearer ' + self.access_token
TypeError: Can't convert 'NoneType' object to str implicitly
```

This exception doesn't occur with `google-api-python-client==1.4.1`, so 1.4.2 is definitely the culprit.

Could you please look into this and fix it?

Thx,
László

**Comment by karolyi** [comment]
In case you'd ask why I use a hidden method `batch._serialize_request` of batch requests:

As you might know, Google's API has limitations on the payload size bytes *AND* the contained requests. I use this method to see if the compiled requests size aren't bigger than the limit.

**Comment by tmatsuo** [comment]
@karolyi I took a quick look on the diff between 1.4.1 and 1.4.2, but haven't found anything suspicious. Are you using the same code when testing with 1.4.1? Also is it possible for you to provide some repro code?

Thanks,

**Comment by karolyi** [comment]
@tmatsuo Yes, it's the same codebase, only the version is reverted to 1.4.1. What can be interesting is that with using `_serialize_request ` I'm trying to calculate the payload length *before* even shooting any actual requests to the API. (so this could be the reason that the `access_token` is not available at that time.

If this is not eligible to reproduce the bug at your side, I can try to prepare something, but it's a PITA as the codebase I built is pretty complicated.

**Comment by dobesv** [comment]
I'm having the same problem, but I'm not doing anything tricky.

```
import json
creds = json.load(open('dev/etc/google-service-accounts/enterprise.json'))
from httplib2 import Http
from oauth2client.client import SignedJwtAssertionCredentials

credentials = SignedJwtAssertionCredentials(
            creds['client_email'],
            creds['private_key'],
            'https://www.googleapis.com/auth/androidenterprise'
        )
http = credentials.authorize(Http())
from googleapiclient.discovery import build
service = build('androidenterprise', 'v1', http=http)
batch = service.new_batch_http_request()
batch.add(service.installs().update(userId='1', enterpriseId='2', deviceId='3', installId='4', body={}))
batch.add(service.installs().update(userId='2', enterpriseId='2', deviceId='4', installId='4', body={}))
batch.add(service.installs().update(userId='3', enterpriseId='2', deviceId='5', installId='4', body={}))
batch.execute()
```

Yields

```
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/oauth2client/util.py", line 142, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "build/bdist.linux-x86_64/egg/googleapiclient/http.py", line 1306, in execute
    self._execute(http, self._order, self._requests)
  File "build/bdist.linux-x86_64/egg/googleapiclient/http.py", line 1230, in _execute
    body = self._serialize_request(request)
  File "build/bdist.linux-x86_64/egg/googleapiclient/http.py", line 1101, in _serialize_request
    request.http.request.credentials.apply(headers)
  File "build/bdist.linux-x86_64/egg/oauth2client/client.py", line 643, in apply
    headers['Authorization'] = 'Bearer ' + self.access_token
TypeError: cannot concatenate 'str' and 'NoneType' objects
````

Note that if I run another request (that is not a batch request) prior to running a batch request, it works.  So something is not being initialized properly for the batch request.

**Comment by dobesv** [comment]
As a workaround, I can force refresh the credentials prior to use:

```
import json
creds = json.load(open('dev/etc/google-service-accounts/enterprise.json'))
from httplib2 import Http
from oauth2client.client import SignedJwtAssertionCredentials

credentials = SignedJwtAssertionCredentials(
            creds['client_email'],
            creds['private_key'],
            'https://www.googleapis.com/auth/androidenterprise'
        )
http = credentials.authorize(Http())
credentials.refresh(http)  # batch() doesn't refresh the access_token on time
from googleapiclient.discovery import build
service = build('androidenterprise', 'v1', http=http)
batch = service.new_batch_http_request()
batch.add(service.installs().update(userId='1', enterpriseId='2', deviceId='3', installId='4', body={}))
batch.add(service.installs().update(userId='2', enterpriseId='2', deviceId='4', installId='4', body={}))
batch.add(service.installs().update(userId='3', enterpriseId='2', deviceId='5', installId='4', body={}))
batch.execute()
```

**Comment by dobesv** [comment]
In the `OAuth2Credentials` class, the code to setup the initial access_token looks like this:

```
        def new_request(uri, method='GET', body=None, headers=None,
                        redirections=httplib2.DEFAULT_MAX_REDIRECTS,
                        connection_type=None):
            if not self.access_token:
                logger.info('Attempting refresh to obtain '
                            'initial access_token')
                self._refresh(request_orig)
```

So, it assumes the `access_token` is not `None` in `apply`.  I'm not sure of the best overall fix here.  I think for my puposes I can do a refresh as soon as I make the http instance with creds, I think that isn't too costly.

**Comment by karolyi** [comment]
This got fixed with 1.5.0, thx.

**Comment by maxb** [comment]
Note for anyone ending up here via Google - the affected version is still present in the new Ubuntu LTS 16.04 Xenial Xerus.

**Comment by kkurian** [comment]
Seeing this issue intermittently in 1.5.1.

The following workaround, which builds off of the [previously reported workaround](https://github.com/google/google-api-python-client/issues/137#issuecomment-159116338), resolves the issue for me so far:

```
try:
    batch.execute()
except TypeError:
    credentials.refresh(http)
    batch.execute()
```

**Comment by mjmvisser** [comment]
I also still see the same problem consistently in 1.5.1. If the first request is via BatchHttpRequest, I get this error:

    Traceback (most recent call last):                                                                               
      File "<stdin>", line 1, in <module>                                                                            
      File "/home/mvisser/workspace/pipelinetools/python/mokgoogle/gmailhandler.py", line 158, in insertUsersInGroup 
        batch.execute()                                                                                              
      File "/prod/tools/common/lib/python2.7/site-packages/oauth2client/util.py", line 137, in positional_wrapper    
        return wrapped(*args, **kwargs)                                                                              
      File "/prod/tools/common/lib/python2.7/site-packages/googleapiclient/http.py", line 1397, in execute           
        self._execute(http, self._order, self._requests)                                                             
      File "/prod/tools/common/lib/python2.7/site-packages/googleapiclient/http.py", line 1321, in _execute          
        body = self._serialize_request(request)                                                                      
      File "/prod/tools/common/lib/python2.7/site-packages/googleapiclient/http.py", line 1192, in _serialize_request
        request.http.request.credentials.apply(headers)                                                              
      File "/prod/tools/common/lib/python2.7/site-packages/oauth2client/client.py", line 577, in apply               
        headers['Authorization'] = 'Bearer ' + self.access_token                                                     
    TypeError: cannot concatenate 'str' and 'NoneType' objects    

If any non-batch request is performed first, the error doesn't occur.

Forcing a credentials refresh immediately after acquiring them works (thanks @kkurian!):

    credentials = ServiceAccountCredentials.from_p12_keyfile(SERVICE_ACCOUNT_EMAIL,
                                                             SERVICE_ACCOUNT_PKCS12_FILE_PATH,
                                                             scopes=['https://www.googleapis.com/auth/admin.directory.group',
                                                                    'https://www.googleapis.com/auth/admin.directory.user'])
    delegated_credentials = credentials.create_delegated(admin_user_email)
    http = httplib2.Http()
    http = delegated_credentials.authorize(http)
        
    delegated_credentials.refresh(http)

**Comment by karolyi** [comment]
reopening as it is definitely not fixed.

**Comment by jonparrott** [comment]
Since there is a bug on the upstream oauth2client (linked above) this issue is not with this library. I'm reclosing.
